name: Docker

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/arm64
          tags: 
            - lengyue233/onnxruntime-l4t:latest
            - lengyue233/onnxruntime-l4t:l4t-32.5-py-3.9-ort-1.8
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
